# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
# 

Name:       sailfishos-uithemer

# >> macros
# << macros

%{!?qtc_qmake:%define qtc_qmake %qmake}
%{!?qtc_qmake5:%define qtc_qmake5 %qmake5}
%{!?qtc_make:%define qtc_make make}
%{?qtc_builddir:%define _builddir %qtc_builddir}
Summary:        UI Themer
Version:        0.6.3
Release:        8
Group:          Qt/Qt
License:        GPLv3
Packager:       fravaccaro <fravaccaro@jollacommunity.it>
URL:            https://github.com/fravaccaro/sailfishos-uithemer
Source0:        %{name}-%{version}.tar.bz2
Source100:      sailfishos-uithemer.yaml
Requires:       sailfish-version >= 2.1.0, harbour-themepacksupport >= 0.5.0-6
BuildRequires:  pkgconfig(sailfishapp) >= 1.0.2
BuildRequires:  pkgconfig(Qt5Core)
BuildRequires:  pkgconfig(Qt5Qml)
BuildRequires:  pkgconfig(Qt5Quick)
BuildRequires:  desktop-file-utils

%description
Enables customization of icons, fonts and pixel density in Sailfish OS.


%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%preun
if [ "$1" = "0" ]; then
    rm -rf /home/nemo/.local/share/sailfishos-uithemer
    filepath="/usr/share/applications/harbour-themepacksupport.desktop"
    if [ -e "$filepath" ]; then
        if grep -q NoDisplay "$filepath"; then
            cont=$(cat $filepath)
            replace=""
            repl=${cont//NoDisplay=true/$replace}
            echo "$repl" > $filepath
        fi
    fi
fi

%build
# >> build pre
# << build pre

%qtc_qmake5 

%qtc_make %{?_smp_mflags}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%qmake5_install

# >> install post
# << install post

desktop-file-install --delete-original       \
  --dir %{buildroot}%{_datadir}/applications             \
   %{buildroot}%{_datadir}/applications/*.desktop

%files
%defattr(4755,root,root,-)
%{_bindir}
%{_datadir}/%{name}
%{_datadir}/applications/%{name}.desktop
%{_datadir}/icons/hicolor/*/apps/%{name}.png
# >> files
# << files

%changelog
* Tue Jul 4 2017 0.6.2
- Display density page polished.
- Icon updater page polished.
- Translations updated.

* Sat Jul 1 2017 0.6.1
- Added auto-update icons option.

* Thu Jun 29 2017 0.6.0
- Recovery tools added.

* Sat Apr 22 2017 0.5.9
- Notifications added
- Dutch translation updated.

* Sat Apr 22 2017 0.5.6
- Added Dutch translation (thanks to Nathan Follens).
- Added German translation (thanks to Sailfishman).

* Thu Apr 18 2017 0.5.5
- Added Polish translation (thanks to Tomasz Amborski).

* Tue Apr 18 2017 0.5.4
- Minor fixes.

* Sat Apr 15 2017 0.5.3
- Minor fixes.

* Sat Apr 15 2017 0.5.2
- Android DPI settings.
- Compatibility with Theme pack support 0.3.3.

* Sat Apr 15 2017 0.5.1
- Bug fix.
- Compatibility with Theme pack support 0.3.2.
